targets:
  $default:
    sources:
      exclude:
        - test/**
    builders:
      # See https://pub.dev/packages/json_serializable
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      build_version:
        options:
          output: lib/src/_version.dart
