name: clerk_sdk

packages:
  - packages/**
  - example/**

ide:
  intellij:
    enabled: true
    moduleNamePrefix: ''

scripts:
  # Clean all packages
  clean:
    name: Clean all
    description: Run flutter clean in all packages
    run: melos exec -- fvm flutter clean

  # Pub get all packages
  get:
    name: Get all
    description: Run pub get in all packages
    run: melos exec -o -- fvm flutter pub get

  # Pub upgrade all packages
  upgrade:
    name: Upgrade all
    description: Run pub upgrade in all packages
    run: melos exec -o -- fvm flutter pub upgrade

  # Build runner (code generation)
  brunner:
    run: melos exec -o -- fvm dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: 'clerk_auth'

  # Format code
  format:
    run: melos exec -- fvm dart format --line-length=80 MELOS_PACKAGE_PATH

  # Run build and format code
  brunner_format:
    run: melos run brunner && melos run format

  # Run localizations
  localization:
    run: melos run sort_localizations && melos exec -- fvm flutter gen-l10n && melos run format
    packageFilters:
      scope: "clerk_flutter"

  # Sort localizations `dart pub global activate arb_utils`
  sort_localizations:
    run: melos exec -- arb_utils sort l10n/en.arb
    packageFilters:
      scope: "clerk_flutter"
