name: clerk_flutter
description: Package that will allow you to authenticate and use Clerk from Flutter code.
version: 0.0.8-beta
homepage: https://clerk.com/docs
repository: https://github.com/clerk/clerk-sdk-flutter/tree/main/packages/clerk_flutter
issue_tracker: https://github.com/clerk/clerk-sdk-flutter/labels/clerk_flutter
publish_to: none
topics:
  - authentication

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: 1.10.1
  clerk_auth:
    path: ../clerk_auth
  collection: 1.19.1
  email_validator: 3.0.0
  flutter_svg: 2.0.17
  image_picker: 1.0.7
  path_provider: 2.1.2
  phone_input: 1.0.0
  webview_flutter: 4.5.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
