name: clerk_flutter_example
description: Example application for linking to clerk_flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  clerk_flutter:
    path: ../
  clerk_auth:
    git:
      url: https://github.com/clerk/clerk-sdk-flutter.git
      path: packages/clerk_auth
      ref: main

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
