name: clerk_widgetbook
description: A widgetbook for clerk_flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  clerk_flutter:
    path: ../clerk_flutter
  flutter_svg: ^2.0.10+1
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: any
  flutter_lints: ^3.0.1
  widgetbook_generator: ^3.9.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
